pipeline {
    agent {
        kubernetes {
            yaml """
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: jenkins-kaniko
spec:
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:latest
    command:
    - cat
    tty: true
"""
        }
    }
    stages {
        stage('Build & Push Docker Image with Kaniko') {
            steps {
                container('kaniko') {
                    withCredentials([usernamePassword(credentialsId: 'dockerhub1', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                        sh '''
                        /kaniko/executor \
                            --dockerfile `pwd`/Dockerfile \
                            --context `pwd` \
                            --destination=${DOCKER_USER}/${APP_NAME}:${IMAGE_TAG} \
                            --destination=${DOCKER_USER}/${APP_NAME}:latest
                        '''
                    }
                }
            }
        }
    }
}

