apiVersion: v1
kind: Service
metadata:
  name: complete-production-pipeline
spec:
  selector:
    app: complete-production-pipeline
  ports:
    nodePort: 30080
    - port: 80        # the port that the service exposes
      targetPort: 8080  # the port on the Pod
  type: NodePort


